version: '3'
services:
  hugo:
    image: klakegg/hugo:0.111.0-ext-ubuntu
    command: server -s /app/src --enableGitInfo=false --verbose --debug --minify
    volumes:
      - ".:/app"
    ports:
      - "1313:1313"